[2025-01-05T06:33:31.215+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T06:33:31.237+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.store_user manual__2025-01-05T06:33:14.286564+00:00 [queued]>
[2025-01-05T06:33:31.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.store_user manual__2025-01-05T06:33:14.286564+00:00 [queued]>
[2025-01-05T06:33:31.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T06:33:31.273+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_user> on 2025-01-05 06:33:14.286564+00:00
[2025-01-05T06:33:31.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2025-01-05T06:33:14.286564+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmprh0r76co']
[2025-01-05T06:33:31.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1097) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T06:33:31.290+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask store_user
[2025-01-05T06:33:31.292+0000] {standard_task_runner.py:72} INFO - Started process 1099 to run task
[2025-01-05T06:33:31.366+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.store_user manual__2025-01-05T06:33:14.286564+00:00 [running]> on host a67ecbd59b00
[2025-01-05T06:33:31.462+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='store_user' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T06:33:14.286564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T06:33:14.286564+00:00'
[2025-01-05T06:33:31.465+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T06:33:31.466+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T06:33:31.466+0000] {logging_mixin.py:190} INFO - Current task name:store_user state:running start_date:2025-01-05 06:33:31.238414+00:00
[2025-01-05T06:33:31.467+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2025-01-05T06:33:31.468+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T06:33:31.469+0000] {postgres.py:196} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processes_user.csv
[2025-01-05T06:33:31.479+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-01-05T06:33:31.485+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-05T06:33:31.497+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T06:33:31.498+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, run_id=manual__2025-01-05T06:33:14.286564+00:00, execution_date=20250105T063314, start_date=20250105T063331, end_date=20250105T063331
[2025-01-05T06:33:31.508+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T06:33:31.509+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T06:33:31.509+0000] {logging_mixin.py:190} INFO - Dag name:user_processing queued_at:2025-01-05 06:33:14.312623+00:00
[2025-01-05T06:33:31.510+0000] {logging_mixin.py:190} INFO - Task hostname:a67ecbd59b00 operator:PythonOperator
[2025-01-05T06:33:31.551+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T06:33:31.580+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T06:33:31.588+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
