[2025-01-05T06:06:49.432+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T06:06:49.454+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-01-05T06:06:43.468299+00:00 [queued]>
[2025-01-05T06:06:49.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available manual__2025-01-05T06:06:43.468299+00:00 [queued]>
[2025-01-05T06:06:49.466+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T06:06:49.487+0000] {taskinstance.py:2889} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-05 06:06:43.468299+00:00
[2025-01-05T06:06:49.499+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=680) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T06:06:49.501+0000] {standard_task_runner.py:72} INFO - Started process 682 to run task
[2025-01-05T06:06:49.502+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-01-05T06:06:43.468299+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpoo411wgp']
[2025-01-05T06:06:49.503+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask is_api_available
[2025-01-05T06:06:49.563+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-01-05T06:06:43.468299+00:00 [running]> on host a67ecbd59b00
[2025-01-05T06:06:49.662+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T06:06:43.468299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T06:06:43.468299+00:00'
[2025-01-05T06:06:49.664+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T06:06:49.665+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T06:06:49.666+0000] {logging_mixin.py:190} INFO - Current task name:is_api_available state:running start_date:2025-01-05 06:06:49.455365+00:00
[2025-01-05T06:06:49.667+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2025-01-05T06:06:49.667+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T06:06:49.668+0000] {baseoperator.py:416} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2025-01-05T06:06:49.669+0000] {http.py:137} INFO - Poking: api/
[2025-01-05T06:06:49.680+0000] {base.py:84} INFO - Retrieving connection 'user_api'
[2025-01-05T06:06:51.402+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2025-01-05T06:06:51.420+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T06:06:51.421+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=manual__2025-01-05T06:06:43.468299+00:00, execution_date=20250105T060643, start_date=20250105T060649, end_date=20250105T060651
[2025-01-05T06:06:51.440+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-05T06:06:51.441+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-05T06:06:51.442+0000] {logging_mixin.py:190} INFO - Dag name:user_processing queued_at:2025-01-05 06:06:43.497235+00:00
[2025-01-05T06:06:51.443+0000] {logging_mixin.py:190} INFO - Task hostname:a67ecbd59b00 operator:HttpSensor
[2025-01-05T06:06:51.490+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T06:06:51.532+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-05T06:06:51.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
